# Generated by Django 5.1.7 on 2025-03-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_ingredient_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
